baseURL = "https://hengdream.space/"
languageCode = "en-us"
title = "Heng's Dream Blog"
theme = "PaperMod"

[params]
author = "Heng"
ShowReadingTime = true
ShowToc = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
